---
- name: This is a hello-world example
  hosts: all
  vars:
    - source_path: "python_files"
    - test_script_name: "test.py"
    - python_requirements: "requirements.txt"

  tasks:
    - name: Copy src files to hosts with new permissions
      ansible.builtin.copy:
        src: python_files/
        dest: ~/syrmia_test_awx/
        mode: a+x
    - name: Install python libraries
      command: pip install -r "{{python_requirements}}"
      args:
        chdir: ~/syrmia_test_awx/
    - name: Execute test script
      command: python3 "{{ test_script_name }}"
      args:
        chdir: ~/syrmia_test_awx/
