- name: Hello World Sample
  hosts: all
  vars:
    directory: /var/lib  
  tasks:
    - command: "ls {{directory}}"
    register: dir_out
    - debug: var={{item}}
    with_items: dir_out.stdout_lines
    - name: Hello Message
      debug:
        msg: "Hello World!"

