name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      run: |
        echo $AWX_OPERATOR | docker login ghcr.io -u banekg --password-stdin
      env:
        CR_PAT: ${{ secrets.AWX_OPERATOR }}
