---
- name: This is a playbook for test
  hosts: all
  vars:
    - source_path: "python_files"
    - test_script_name: "test.py"

  tasks:
    - name: Hello world on machine 1
      when: inventory_hostname in groups['Syrmia_VM_Client']
      command: echo hello world 1
    - name: Hello world on machine 2
      when: inventory_hostname in groups['Syrmia_VM_Server']
      command: echo hello world 2
